C_OPTIONS_SHELL=$1
EXEFILE_SHELL=$2
PROBLEMPATH_SHELL=$3
USERNAME=$4
SUBMIT_NAME=$5

cp $PROBLEMPATH_SHELL/main.cpp .
#cp $PROBLEMPATH_SHELL/*.h .

g++ -std=c++17 main.cpp FileOpts.cpp -o $EXEFILE_SHELL